package hl.quizonline.config;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import hl.quizonline.entity.Account;
import hl.quizonline.entity.Category;
import hl.quizonline.enumrable.Gender;
import hl.quizonline.service.AccountService;
import hl.quizonline.service.CategoryService;

@Component
public class AutoGenerateData implements ApplicationListener<ContextRefreshedEvent> {

	@Autowired
	CategoryService categoryService;
	
	@Autowired
	AccountService accountService;
	
	@Autowired
	PasswordEncoder passwordEncoder;
	
	@Override
	public void onApplicationEvent(ContextRefreshedEvent event) {
		//generate categories
		
		if(!categoryService.exist("Khác")) {
			Category c = new Category("Khác");
			categoryService.create(c);
		}
		if(!categoryService.exist("Toán")) {
			Category c = new Category("Toán");
			categoryService.create(c);
		}
		if(!categoryService.exist("Văn")) {
			Category c = new Category("Văn");
			categoryService.create(c);
		}
		if(!categoryService.exist("Lịch sử")) {
			Category c = new Category("Lịch sử");
			categoryService.create(c);
		}
		System.out.println("Tạo các danh mục mẫu thành công");
		
		//Tạo ra tài khoản admin
		if(accountService.getAccountByUsername("admin").isEmpty()) {
			Account acc = new Account(0, new Date(System.currentTimeMillis()), 
					"admin", 
					passwordEncoder.encode("123456"), 
					Gender.MALE, 
					null, 
					"admin", 
					true, 
					"ROLE_ADMIN", null, null);
			accountService.registerAccount(acc);
		}
		
		System.out.println("Tạo tài khoản admin thành công");
	}

}
